version: '3.8'

services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    
  kafka:
    image: confluentinc/cp-kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=192.0.0.2:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.0.0.2:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - kafka